name: CI/CD Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: prepare unit test
        run: |
          sudo apt update
          sudo apt install -y python3-pip
          pip install -r ./part_service/requirements.txt
          echo "TEST_BUILD = TRUE
          AMQP_URL=''
          POSTGRES_URL=''
          KEYCLOAK_ID=''
          KEYCLOAK_SECRET=''
          KEYCLOAK_URL=''
          KEYCLOAK_REALM=''" > .env

      - name: prepare unit test
        run: |
          pip install -r ./repair_service/requirements.txt
      
      - name: run unit test
        run: |
          pytest ./repair_service/app/tests/unit

      - name: run unit test
        run: |
          pytest ./part_service/app/tests/unit

      - name: prepare e2e test
        run: |
          sudo docker build -t part-test ./part_service
          sleep 10
          docker run -e TEST_BUILD=TRUE -e AMQP_URL="" -e POSTGRES_URL="" -e KEYCLOAK_ID="" -e KEYCLOAK_SECRET="" -e KEYCLOAK_URL="" -e KEYCLOAK_REALM="" -d -p 81:80 part-test


      - name: prepare e2e test
        run: |
          sudo docker build -t repair-test ./repair_service
          sleep 10
          docker run -e TEST_BUILD=TRUE -e AMQP_URL="" -e PART_URL="" -e POSTGRES_URL="" -e KEYCLOAK_ID="" -e KEYCLOAK_SECRET="" -e KEYCLOAK_URL="" -e KEYCLOAK_REALM="" -v -d -p 82:80 repair-test
          sleep 25

      - name: show info
        run: |
          sudo docker ps -a

      - name: run e2e test
        run: |
          pytest ./part_service/app/tests/endpoint

      - name: run e2e test
        run: |
          pytest ./repair_service/app/tests/endpoint
